import type { Region } from "@/lib/scoring-config";

/** Realistic branch location names for layout preview pages. */
export const PREVIEW_BRANCH_NAMES_BY_REGION: Record<Region, string[]> = {
  luzon: [
    "Baguio",
    "Angeles",
    "Batangas City",
    "Lucena",
    "Naga",
    "Legazpi",
    "Tuguegarao",
    "Laoag",
    "Dagupan",
    "San Fernando (La Union)",
    "Olongapo",
    "Tarlac City",
    "Cabanatuan",
    "San Jose (Nueva Ecija)",
    "Malolos",
    "San Pablo",
    "Lipa",
    "Calamba",
    "Tagaytay",
    "Urdaneta",
    "Vigan",
    "Tabuk",
    "Ilagan",
    "Baler",
    "Infanta",
    "Daet",
    "Sorsogon City",
    "Iriga",
    "Tabaco",
    "Gapan",
    "San Fernando (Pampanga)",
    "Mabalacat",
    "Balanga",
    "Mariveles",
    "San Carlos",
    "Umingan",
    "Bayombong",
    "Solano",
    "Tayabas",
    "Lucban",
    "Santa Cruz",
    "Los Baños",
    "Tanauan",
    "Rosario",
    "Bauan",
  ],
  ncr: [
    "Manila",
    "Quezon City",
    "Makati",
    "Pasig",
    "Taguig",
    "Mandaluyong",
    "Parañaque",
    "Las Piñas",
    "Muntinlupa",
    "Caloocan",
    "Valenzuela",
    "Malabon",
    "Navotas",
    "San Juan",
    "Marikina",
    "Pasay",
    "Pateros",
    "Antipolo",
    "Cainta",
    "Taytay",
    "Binangonan",
    "Angono",
    "Rodriguez",
    "San Mateo",
    "Quezon City — North",
    "Quezon City — South",
    "Makati — Ayala",
    "Makati — Poblacion",
    "Taguig — BGC",
    "Taguig — Signal",
    "Pasig — Ortigas",
    "Pasig — Kapitolyo",
    "Manila — Ermita",
    "Manila — Binondo",
    "Manila — Sampaloc",
    "Caloocan — North",
    "Caloocan — South",
    "Parañaque — BF",
    "Las Piñas — Alabang",
    "Muntinlupa — Alabang",
    "Marikina — Shoe Ave",
    "Valenzuela — McArthur",
    "Malabon — Bayan",
    "Navotas — Fish Port",
  ],
  vismin: [
    "Cebu City",
    "Iloilo City",
    "Bacolod",
    "Davao City",
    "Cagayan de Oro",
    "Zamboanga City",
    "General Santos",
    "Tacloban",
    "Dumaguete",
    "Tagbilaran",
    "Butuan",
    "Cotabato City",
    "Iligan",
    "Ormoc",
    "Roxas City",
    "Puerto Princesa",
    "Pagadian",
    "Dipolog",
    "Surigao City",
    "Kidapawan",
    "Koronadal",
    "Bayawan",
    "Tagum",
    "Panabo",
    "Digos",
    "Malaybalay",
    "Valencia (Bukidnon)",
    "Ozamiz",
    "Tangub",
    "Silay",
    "Borongan",
    "Catbalogan",
    "Maasin",
    "Siquijor",
    "Camiguin",
    "El Nido",
    "Coron",
    "Bantayan",
    "Moalboal",
    "Danao",
    "Lapu-Lapu",
    "Mandaue",
    "Toledo",
    "Carcar",
    "Argao",
  ],
};

export function previewBranchName(region: Region, indexInRegion: number): string {
  const pool = PREVIEW_BRANCH_NAMES_BY_REGION[region];
  return pool[indexInRegion % pool.length];
}
